id: IEE67309C
initial_creation_type: ebook
source_metadata:
  id: RDI-KK-17
  title: བསྙེན་ཡིག་སྣ་ཚོགས་ཕྱོགས་བསྡེབས་པད་དཀར་ཆུན་པོ།
  author: མཛད་པ་པོ། ཏཱའ་ར་ནཱ་ཐ།, མཛད་པ་པོ། མཁས་གྲུབ་རཱ་ག་ཨསྱ།, མཛད་པ་པོ། འཇམ་མགོན་ཀོང་སྤྲུལ་བློ་གྲོས་མཐའ་ཡས།,
    མཛད་པ་པོ། ཚེ་དབང་ཀུན་ཁྱབ།
  authors: &id001
  - མཛད་པ་པོ། ཏཱའ་ར་ནཱ་ཐ།
  - མཛད་པ་པོ། མཁས་གྲུབ་རཱ་ག་ཨསྱ།
  - མཛད་པ་པོ། འཇམ་མགོན་ཀོང་སྤྲུལ་བློ་གྲོས་མཐའ་ཡས།
  - མཛད་པ་པོ། ཚེ་དབང་ཀུན་ཁྱབ།
  sku: RDI-KK-17
  cover: RDI-KK-17.jpeg
  volume: {}
  series: དྭགས་བརྒྱུད་སྒྲུབ་པའི་ཐེམ་སྐས་གདམས་ངག་ཕྱོགས་བསྒྲིགས།
  title_source: epub:dc:title:ambiguous-layer
ebook_metadata:
  title: བསྙེན་ཡིག་སྣ་ཚོགས་ཕྱོགས་བསྡེབས་པད་དཀར་ཆུན་པོ།
  authors: *id001
  sku: RDI-KK-17
  cover: RDI-KK-17.jpeg
layers:
- Author
- BookNumber
- BookTitle
- Chapter
- Citation
- Commentary
- Footnote
- Sabche
- Tsawa
- Yigchung
